traffic_access/auth.py
"""
Routes of authentication in this app.

AUTHOR: Keiber Urbila
CREATION DATE: 10/06/21
"""
from flask import Blueprint, render_template, request, flash, redirect, \
    url_for, abort
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from modules.auth import is_safe_url
from .models import User
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    """ Login route """
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        remember = True if request.form.get("remember") else False

        user = User.query.filter_by(email=email).first()
        if not user or not check_password_hash(user.password, password):
            flash("Invalid credentials. please check and try again.")
            return redirect(url_for("auth.login"))

        login_user(user, remember=remember)

        if request.form.get("next") != "None":
            next_page = request.form.get("next")
        else:
            next_page = False

        # is_safe_url should check if the url is safe for redirects.
        # See http://flask.pocoo.org/snippets/62/ for an example.
        if not is_safe_url(next_page):
            return abort(400)
        return redirect(next_page or url_for('trends.index'))

    return render_template("login_form.html")


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        password_check = request.form.get("password_check")

        # Email validator
        if len(email.partition("@")[0]) < 4:
            flash("Email username must be at least 4 characters long.")
            return redirect(url_for("auth.signup"))

        # Password validator
        if password != password_check:
            flash("Passwords do not match.")
            return render_template("signup_form.html")

        user = User.query.filter_by(email=email).first()

        if user:
            flash("User already exists.")
            return redirect(url_for("auth.signup"))

        new_user = User(username=email.partition("@")[0],
                        email=email,
                        password=generate_password_hash(password,
                                                        method="sha256"))

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for("auth.login"))

    return render_template("signup_form.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

traffic_access/views.py
"""
Routes from traffic_charts route

AUTHOR: Keiber Urbila
CREATION DATE: 10/06/21
"""
import io
import pandas as pd
from modules import query_db
from modules.trend import chart_trend, get_dataframe_pivoted_by_date
from flask import render_template, request, session, url_for, redirect, \
    make_response, Blueprint
from flask_login import login_required


def validate_form(city: str, company: str, firstday: str, lastday: str):
    """ Validate form and save query as session """
    data_form = {"city": city, "company": company}

    if firstday is None:
        session["firstday"] = "2021-04-01"
    else:
        session["firstday"] = firstday

    if lastday is None:
        session["lastday"] = "2021-04-07"
    else:
        session["lastday"] = lastday

    for index, value in data_form.items():
        try:
            session[index] = value if value is not None else session[index]

        except KeyError:  # if session dont exist. Create a session null
            session[index] = None
            print(f"was error with {index}: {value}")


trends = Blueprint("trends", __name__)


@trends.route("/")
@login_required
def index():
    """ Homepage for trends route """

    validate_form(request.args.get("city"),
                  request.args.get("company"),
                  request.args.get("firstday"),
                  request.args.get("lastday"))

    if session["city"] is None:
        return render_template("layout_trends.html",
                               zip=zip,
                               lastday=session["lastday"],
                               firstday=session["firstday"])

    measurements = query_db.Measurements(session["city"],
                                         firstday=session["firstday"],
                                         lastday=session["lastday"])

    # get df from trends in database
    df = measurements.get_trend(session["company"])

    del measurements  # del object of memory

    graph_json = chart_trend(data=df.copy(),
                             city=session["city"],
                             company=session['company'].title())

    try:
        df, dates, elements = get_dataframe_pivoted_by_date(df=df,
                                                            date_list=True,
                                                            element_list=True,
                                                            add_suffix=True)
    except ValueError:
        return render_template("layout_trends.html",
                               zip=zip,
                               lastday=session["lastday"],
                               firstday=session["firstday"])

    return render_template("layout_trends.html",
                           column_names=dates,
                           elements_name=elements,
                           graph_json=graph_json,
                           row_data=list(df.values.tolist()),
                           city=session["city"],
                           company=session["company"],
                           zip=zip,
                           lastday=session["lastday"],
                           firstday=session["firstday"])


@trends.route("/clean")
def clean_sessions():
    """ Clean all session saved """
    for i in ("city", "company", "firstday", "lastday"):
        try:
            session.pop(i, None)
        except KeyError:  # if session dont exist
            pass

    return redirect(url_for("trends.index"))


@trends.route("/download")
@login_required
def download():
    " Download file excel with the values shown in the HTML table"
    measurements = query_db.Measurements(session["city"],
                                         firstday=session["firstday"],
                                         lastday=session["lastday"])

    # get df from trends in database
    df = measurements.get_trend(session["company"])

    if session.get("subgroup"):
        df = df[df["Element"].str.startswith(session["subgroup"])]
        session.pop("subgroup")

    del measurements  # del object of memory

    df, _, _ = get_dataframe_pivoted_by_date(df=df,
                                             date_list=False,
                                             element_list=False,
                                             add_suffix=False)
    # Instantiate byte type IO object, used to store object in memory
    out = io.BytesIO()

    # Create sheet_name
    writer = pd.ExcelWriter(out, engine="xlsxwriter")

    sheetname = "Sheet"

    df.to_excel(writer, sheet_name=sheetname)

    # Auto length for columns
    for column in df:
        column_length = max(df[column].astype(str).map(len).max(),
                            len(column))
        col_idx = df.columns.get_loc(column)
        writer.sheets[sheetname].set_column(col_idx, col_idx, column_length)

    # Save df excel in the memory writer variable, do not include number index
    writer.save()

    # Reset the pointer of the IO object to the beginning
    out.seek(0)

    # The IO object uses get value() to return the binary raw data.
    resp = make_response(out.getvalue())

    # Set the response header to let browser resolve to the file download
    # behavior.
    resp.headers["Content-Disposition"] = (
        f"attachment; filename={session['city']}_{session['company']}.xlsx"
    )
    resp.headers["Content-Type"] = "application/vnd.ms-excel; charset=utf-8"
    return resp

traffic_access/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="author" content="Keiber Urbila" />
    <link
      rel="icon"
      href="{{ url_for('static', filename='imgs/favicon.ico') }}"
      type="image/x-icon"
    />
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet"
      type=text/css
      media="screen"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    >
    <!-- Custom styles for this template -->
    <link rel="stylesheet"
      type=text/css
      media="screen"
      href="{{ url_for('static', filename='css/style.css') }}"
    >
    <!-- Font Awesome -->
    {{ fontawesome_html() }}
    <title>TrafficAccess</title>
    {% endblock %}
  </head>
  <body>
    {% if hidde_img_animated %} {% else %}
    <img
      class="background-img"
      src="{{ url_for('static', filename='imgs/network-globe.png') }}"
      alt=""
    />
    {% endif %} {% block navigation %}
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="{{ url_for('trends.index') }}"
          ><i class="fas fa-project-diagram"></i> TRAFFIC ACCESS</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse"
          style="font-weight: bold"
          id="navbarNav"
        >
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a
                class="nav-link"
                href="https://github.com/metalpoch/"
                target="_blank"
                ><i class="fa fa-github-alt"></i> GitHub</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="https://www.instagram.com/keiberup/"
                target="_blank"
                ><i class="fa fa-instagram"></i> Instagram</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="{{ url_for('show_cv') }}"
                target="_blank"
              >
                <i class="fas fa-id-card"></i> CV
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="cursor: default"> | </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link"
                ><i class="fa fa-user-circle"></i>
                {{ current_user.username }}</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}"
                ><i class="fa fa-door-open"></i> Logout</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}"
                ><i class="fa fa-user-circle"></i> Login</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signup') }}"
                ><i class="fa fa-user-plus"></i> Signup</a
              >
            </li>

            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    {% endblock %} {% block content %} {% endblock %}
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    {% block footer %} {% endblock %}
  </body>
</html>

traffic_access/templates/layout_trends.html
{% extends 'base.html' %}
{% block content %}
<div class="wrapper">
  <nav id="sidebar">
    <ul class="lisst-unstyled components">
      {% include 'components/sidebarMenu/barcelona.html' %}
      {% include 'components/sidebarMenu/barquisimeto.html' %}
      {% include 'components/sidebarMenu/cagua.html' %}
      {% include 'components/sidebarMenu/caracas.html' %}
      {% include 'components/sidebarMenu/guarenas.html' %}
      {% include 'components/sidebarMenu/maracaibo.html' %}
      {% include 'components/sidebarMenu/maracay.html' %}
      {% include 'components/sidebarMenu/porlamar.html' %}
      {% include 'components/sidebarMenu/puerto-cabello.html' %}
      {% include 'components/sidebarMenu/turmero.html' %}
      <li class="active"></li>
    </ul>
  </nav>
  <div class="container-fluid pl-1 pt-2 mx-0">
    <a id="sidebarCollapse" class="text-light">
      <i class="fas fa-bars"></i> Menu
    </a>
    <a
      href="{{ url_for('trends.clean_sessions') }}"
      id="sidebarCollapse"
      class="pl-2 text-light"
    >
      <i class="fas fa-brush"></i> Clean
    </a>
    <!-- Main Content Here -->
    <div class="container pt-3">
      {% include 'components/dataFrame/form.html' %}
      <div class="row my-4">
        <div class="container bg-semidark rounded">
          {% include 'components/dataFrame/chart.html' %}
        </div>
      </div>
      <div class="row">
        <div class="rounded df-table">
          {% if column_names %}
          <a
            class="btn btn-info float-right mb-1"
            href="{{ url_for('trends.download') }}"
            >Download <i class="fas fa-file-download"></i
          ></a>
          {% include 'components/dataFrame/table.html' %}
	  {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block footer %}
<script>
  $(document).ready(function () {
    $("#sidebarCollapse").on("click", function () {
      $("#sidebar").toggleClass("active");
    });
  });
</script>
{% endblock %}

traffic_access/templates/login_form.html
{% extends 'base.html' %} {% block head %} {{ super() }} <link rel="stylesheet"
type=text/css media="screen" href="{{ url_for('static', filename='css/login_form.css')

}}" > {% endblock %} {% block content %}
<main role="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2"></div>
      <div class="col-lg-6 col-md-8 login-box">
        <div class="col-lg-12 login-key pt-3">
          <i class="fa fa-user-lock" aria-hidden="true"></i>
        </div>
        <div class="col-lg-12 login-title">LOGIN</div>
        {% with messages = get_flashed_messages() %} {% if messages %} {% for
        message in messages %}
        <div
          class="alert alert-danger alert-dismissible text-center mr-5 ml-5"
          role="alert"
        >
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">×</span>
          </button>
          {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}
        <div class="col-lg-12 login-form">
          <div class="col-lg-12 login-form">
            <form action="{{ url_for('auth.login') }}" method="POST">
              <div class="form-group">
                <input
                  type="hidden"
                  name="next"
                  value="{{ request.args.get('next') }}"
                />
                <label class="form-control-label">EMAIL</label>
                <input
                  type="text"
                  class="form-control"
                  name="email"
                  required
                />
              </div>
              <div class="form-group">
                <label class="form-control-label">PASSWORD</label>
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  required
                  minlength="8"
                />
              </div>
              <div class="col-lg-12 loginbttm">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    name="remember"
                    type="checkbox"
                    value="remember"
                    id="flexCheckDefault"
                  />
                  <label class="form-check-label" for="flexCheckDefault">
                    Recuerdame
                  </label>
                </div>
                <div class="float-right login-btm login-button">
                  <button type="submit" class="btn btn-outline-primary">
                    SUBMIT
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

traffic_access/templates/signup_form.html
{% extends 'base.html' %} {% block head %} {{ super() }} <link rel="stylesheet"
type=text/css media="screen" href="{{ url_for('static', filename='css/login_form.css')
}}" > {% endblock %} {% block content %}
<main role="main">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2"></div>
      <div class="col-lg-6 col-md-8 login-box">
        <div class="col-lg-12 login-key">
          <i class="fa fa-key" aria-hidden="true"></i>
        </div>
        <div class="col-lg-12 login-title">CREATE ACCOUNT</div>
        {% with messages = get_flashed_messages() %}
	{% if messages %}
	{% for message in messages %}
        <div
          class="alert alert-danger alert-dismissible text-center mr-5 ml-5"
          role="alert"
        >
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">×</span>
          </button>
          {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}
        <div class="col-lg-12 login-form">
          <div class="col-lg-12 login-form">
            <form action="{{ url_for('auth.signup') }}" method="POST">
              <div class="form-group">
                <label class="form-control-label">EMAIL</label>
                <input
                  type="email"
                  class="form-control"
                  name="email"
                  required
                />
              </div>
              <div class="form-group">
                <label class="form-control-label">PASSWORD</label>
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  required
                  minlength="8"
                />
              </div>
              <div class="form-group">
                <label class="form-control-label">REPEAT PASSWORDS</label>
                <input
                  type="password"
                  class="form-control"
                  name="password_check"
                  required
                  minlength="8"
                />
              </div>
              <div class="col-lg-12 loginbttm">
                <div class="float-right login-btm login-button">
                  <button type="submit" class="btn btn-outline-primary">
                    Create
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}